DIRECTION_LIST: list = ["vertical", "horizontal"]
VERTICAL_DIRECTION: str = "vertical"
HORIZONTAL_DIRECTION: str = "horizontal"

DOCUMENT_LENGTH_THRES: int = 10
MAX_ITERATION: int = 4

NULL: float = 0.0
LINE_THRESHOLD: float = 0.8
LINE_THRESHOLD_LOW: float = 0.1
LINE_MEDIAN_THRESHOLD: float = 2
LINE_MEDIAN_THRESHOLD_LOW: float = 1
VERTICAL_THRES_TOT: float = 10.0
VERTICAL_THRES_SEC: float = 5.0
VERTICAL_THRES_CORR: float = 0.8
FONTSIZE_MIN: float = 1.1
FONTSIZE_DIFFERENCE: float = 0.37
RESCALE_MIN_DIFFERENCE: float = 0.0001
HOR_THRES_TOT: float = 1.0
HOR_THRES_SEC: float = 0.5
HOR_CORRECTION: float = 0.3
MIN_WORDS_IN_COLUMN: int = 5
MAX_WHILE: int = 100
POINTS_MIN_DIFF: float = 1e-2
PDF_CONTENT_TYPE: str = "application/pdf"
ERROR_MESSAGE_IN_TEXT: str = "AN ERROR OCCURS PROCESSING THIS PAGE"

