DOCUMENT_LENGTH_THRES: int = 10

NULL: float = 0.0
LINE_THRESHOLD: float = 0.8
LINE_THRESHOLD_LOW: float = 0.1
LINE_MEDIAN_THRESHOLD: float = 2
LINE_MEDIAN_THRESHOLD_LOW: float = 1


MAX_WHILE: int = 100
POINTS_MIN_DIFF: float = 1e-2
ERROR_MESSAGE_IN_TEXT: str = "AN ERROR OCCURS PROCESSING THIS PAGE"
